version: '2'
services:
  db:
    image: postgres:11.4
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
