import * as dotenv from "dotenv";

dotenv.config();

export const REACT_APP_SERVER_WEBSOCKET = process.env
  .REACT_APP_SERVER_WEBSOCKET!;
export const REACT_APP_SERVER_PROTOCOL = process.env.REACT_APP_SERVER_PROTOCOL!;
export const REACT_APP_SERVER_BASE = process.env.REACT_APP_SERVER_BASE!;
export const REACT_APP_SERVER_GRAPHQL_ENDPOINT = process.env
  .REACT_APP_SERVER_GRAPHQL_ENDPOINT!;

export const WEBSOCKET_ENDPOINT = `${REACT_APP_SERVER_WEBSOCKET}://${REACT_APP_SERVER_BASE}/${REACT_APP_SERVER_GRAPHQL_ENDPOINT}`;
export const HTTP_ENDPOINT = `${REACT_APP_SERVER_PROTOCOL}://${REACT_APP_SERVER_BASE}/${REACT_APP_SERVER_GRAPHQL_ENDPOINT}`;
